# Cloud Build configuration for ChatGuru-ClickUp Middleware
# Este arquivo define o pipeline de CI/CD para Google Cloud

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'chatguru-clickup-middleware'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatguru-clickup-middleware'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - |
        RUST_LOG=info,
        RUN_MODE=production,
        PORT=8080
      - '--set-secrets'
      - |
        CLICKUP_API_TOKEN=clickup-api-token:latest,
        CLICKUP_LIST_ID=clickup-list-id:latest,
        GCP_PROJECT_ID=gcp-project-id:latest

# Define substitutions for flexibility
substitutions:
  _REGION: southamerica-east1
  _SERVICE_NAME: chatguru-clickup-middleware

# Build timeout
timeout: 1200s

# Build logs
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'