# Cloud Build configuration for ChatGuru-ClickUp Middleware
# Este arquivo define o pipeline de CI/CD para Google Cloud

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatguru-clickup-middleware'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chatguru-clickup-middleware:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - |
        RUST_LOG=info,
        RUN_MODE=production
      - '--update-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'

# Build timeout
timeout: 1200s

# Build logs
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'