name: chatguru-clickup-middleware-trigger
description: Automatic build and deploy on push to main branch
github:
  owner: nextlw
  name: ChatGuru_Nordja_inte
  push:
    branch: ^main$
filename: chatguru-clickup-middleware/cloudbuild.yaml
includedFiles:
  - chatguru-clickup-middleware/**
ignoredFiles:
  - "**/*.md"
  - "**/README.*"
  - "**/.gitignore"
  - "**/docs/**"