# Termos que indicam atividade/pedido
# Formato: termo: peso (0-10, maior = mais forte indicador)

# Verbos de ação/solicitação
preciso: 10.0
quero: 9.5
necessito: 9.0
solicito: 8.5
gostaria: 8.0
favor: 7.5
pode: 7.0

# Termos comerciais
comprar: 10.0
pedido: 9.5
orçamento: 9.0
encomenda: 9.0
cotação: 8.5
preço: 8.0
valor: 7.5
custo: 7.0

# Urgência
urgente: 9.0
rápido: 8.0
hoje: 7.5
agora: 7.0
logo: 6.5

# Produtos/quantidades
caixas: 8.0
unidades: 8.0
metros: 7.5
quilos: 7.5
litros: 7.5
peças: 8.0
material: 7.0
produto: 7.5

# Serviços
serviço: 8.0
reparo: 8.5
conserto: 8.5
manutenção: 8.0
instalação: 8.0

# Contextos específicos
entregar: 7.5
enviar: 7.5
buscar: 7.0
agendar: 8.0
marcar: 7.5

# Stems (formas reduzidas para pegar variações)
# Exemplo: "solicit" pega "solicito", "solicitação", "solicitar"
solicit: 8.5
compra: 9.0
encomend: 9.0
orçament: 9.0
