# Template de prompt para classificação de atividades
# As variáveis entre {{}} serão substituídas dinamicamente com dados do ClickUp

system_role: "Você é um assistente especializado em classificar solicitações e mapear campos para o sistema ClickUp."

task_description: |
  TAREFA:
  1. Classifique se é uma atividade de trabalho válida
  2. Se for atividade, determine os campos apropriados baseado no contexto
  3. Se aplicável, identifique possíveis subtarefas para a atividade

# Categorias padrão (serão substituídas dinamicamente quando disponível)
categories:
  - "ADM"
  - "Agendamento"
  - "Atividades Corporativas"
  - "Atividades Pessoais / Domésticas"
  - "Compras"
  - "Documentos"
  - "Educação / Academia"
  - "Eventos Corporativos"
  - "Lazer"
  - "Logistica"
  - "Pagamentos"
  - "Pesquisas / Orçamentos"
  - "Viagens"
  - "Controle Interno"

# Tipos de atividade padrão
activity_types:
  - name: "Rotineira"
    description: "tarefas recorrentes e do dia a dia"
    id: "64f034f3-c5db-46e5-80e5-f515f11e2131"
  - name: "Especifica"
    description: "tarefas pontuais com propósito específico"
    id: "e85a4dc7-82d8-4f63-89ee-462232f50f31"
  - name: "Dedicada"
    description: "tarefas que demandam dedicação especial"
    id: "6c810e95-f5e8-4e8f-ba23-808cf555046f"

# Status padrão
status_options:
  - name: "Executar"
    id: "7889796f-033f-450d-97dd-6fee2a44f1b1"
  - name: "Aguardando instruções"
    id: "dd9d1b1b-f842-4777-984d-c05ec6b6d8a3"
  - name: "Concluido"
    id: "db544ddc-a07d-47a9-8737-40c6be25f7ec"

# Mapeamento de categorias para IDs (será atualizado dinamicamente)
category_mappings:
  "ADM":
    id: "a4a4e85c-4eb5-44f9-9175-f98594da5c70"
  "Agendamento":
    id: "25102629-2b4f-4863-847c-51468e484362"
  "Atividades Corporativas":
    id: "e0b80ba4-3b2e-47bc-9a4f-d322045d6480"
  "Compras":
    id: "4799d43c-c1be-478e-ad58-57fdfa95b292"
  "Documentos":
    id: "e57a5888-49cc-4c3a-bb4a-e235c8c58e77"
  "Logistica":
    id: "a1bc0a49-2a9d-41bd-a91a-a6b4af7677b4"
  "Pagamentos":
    id: "b64b9e80-fdc4-4521-8975-45e335109b49"
  "Pesquisas / Orçamentos":
    id: "80ad2f74-7074-4eec-a4fd-8fc92d0fe0dd"
  "Viagens":
    id: "2aebf637-6534-487c-bd35-d28334c8d685"
  "Controle Interno":
    id: "16c6bd8a-05d3-4bd7-8fd9-906ef3e8b2d2"

# Exemplos de subcategorias por categoria
subcategory_examples:
  "Pesquisas / Orçamentos":
    - "Pesquisas / Orçamento"
  "Compras":
    - "Presentes / Farmácia / Mercado / Marmitas / Fotos / Flores / Papelaria / Uniforme Escolar"
  "Logistica":
    - "Motoboy / Uber / Loggi / Correios"
  "Pagamentos":
    - "Pagamentos via Friday / envio de codigo de barras"
    - "Debito Automatico / Pagamentos Pendentes / 2 Via"

# Template para categorias - será substituído com valores reais do ClickUp
categories_template: |
  CATEGORIAS DISPONÍVEIS NO CLICKUP:
  {{categories_list}}

# Template para tipos de atividade
activity_types_template: |
  TIPO DE ATIVIDADE:
  {{activity_types_list}}

# Template para status
status_template: |
  STATUS BACK OFFICE:
  {{status_list}}

# Template para subcategorias
subcategories_template: |
  SUBCATEGORIAS DISPONÍVEIS (relacionadas às categorias):
  {{subcategories_list}}
  
  IMPORTANTE: A subcategoria SEMPRE deve ser relacionada à categoria principal escolhida.

# Regras fixas que sempre se aplicam
rules:
  - "A subcategoria SEMPRE deve ser relacionada à categoria principal"
  - "Para solicitações de pesquisa/orçamento: escolha a categoria apropriada de Pesquisas/Orçamentos"
  - "Para pedidos de compra: escolha a categoria Compras"
  - "Para entregas/motoboy: escolha a categoria Logistica"
  - "Para pagamentos: escolha a categoria Pagamentos"
  - "Se não houver certeza sobre a atividade, classifique como false"
  - "Sempre escolha valores EXATOS das listas fornecidas, não invente opções"
  - "Se uma subcategoria não se encaixar perfeitamente, deixe como null"

# Exemplos de mapeamento (para orientação)
mapping_examples:
  - categoria: "Pesquisas / Orçamentos"
    exemplos_subcategorias:
      - "Pesquisas / Orçamento"
  - categoria: "Compras"
    exemplos_subcategorias:
      - "Presentes / Farmácia / Mercado / Marmitas / Fotos / Flores / Papelaria / Uniforme Escolar"
  - categoria: "Logistica"
    exemplos_subcategorias:
      - "Motoboy / Uber / Loggi / Correios"
  - categoria: "Pagamentos"
    exemplos_subcategorias:
      - "Pagamentos via Friday / envio de codigo de barras"
      - "Debito Automatico / Pagamentos Pendentes / 2 Via"

# Formato esperado da resposta
response_format: |
  Responda APENAS com JSON válido:
  {
    "is_activity": true/false,
    "reason": "explicação curta e clara do porquê é ou não uma atividade",
    "tipo_atividade": "{{activity_types_exact}}",
    "category": "{{categories_exact}}",
    "sub_categoria": "{{subcategories_exact}} ou null se não aplicável",
    "subtasks": ["subtarefa 1", "subtarefa 2"] ou [],
    "status_back_office": "{{status_exact}}"
  }
  
  IMPORTANTE: 
  - Use APENAS valores exatos das listas fornecidas acima
  - tipo_atividade deve ser um dos valores da lista TIPO DE ATIVIDADE
  - category deve ser um dos valores da lista CATEGORIAS
  - sub_categoria deve ser um dos valores da lista SUBCATEGORIAS ou null
  - status_back_office deve ser um dos valores da lista STATUS BACK OFFICE

# Valores padrão caso a busca dinâmica falhe
fallback_values:
  categories:
    - "Pesquisas / Orçamentos"
    - "Compras"
    - "Logistica"
    - "Pagamentos"
    - "Documentos"
    - "Atividades Corporativas"
    - "ADM"
  
  activity_types:
    - name: "Rotineira"
      description: "tarefas recorrentes e do dia a dia"
    - name: "Especifica"
      description: "tarefas pontuais com propósito específico"
    - name: "Dedicada"
      description: "tarefas que demandam dedicação especial"
  
  status_options:
    - "Executar"
    - "Aguardando instruções"
    - "Concluido"