# Template de prompt para classificação de atividades
# As variáveis entre {{}} serão substituídas dinamicamente com dados do ClickUp

system_role: "Você é um assistente especializado em classificar solicitações e mapear campos para o sistema ClickUp."

task_description: |
  TAREFA:
  1. Classifique se é uma atividade de trabalho válida
    - Se for atividade, determine os campos apropriados baseado no contexto
    - Se aplicável, identifique possíveis subtarefas para a atividade

# Categorias padrão (serão substituídas dinamicamente quando disponível)
categories:
  - "Agendamentos"
  - "Compras"
  - "Documentos"
  - "Lazer"
  - "Logística"
  - "Viagens"
  - "Plano de Saúde"
  - "Agenda"
  - "Financeiro"
  - "Assuntos Pessoais"
  - "Atividades Corporativas"
  - "Gestão de Funcionário"

# Tipos de atividade padrão
activity_types:
  - name: "Rotineira"
    description: "tarefas recorrentes e do dia a dia"
    id: "64f034f3-c5db-46e5-80e5-f515f11e2131"
  - name: "Especifica"
    description: "tarefas pontuais com propósito específico"
    id: "e85a4dc7-82d8-4f63-89ee-462232f50f31"
  - name: "Dedicada"
    description: "tarefas que demandam dedicação especial"
    id: "6c810e95-f5e8-4e8f-ba23-808cf555046f"

# Status padrão
status_options:
  - name: "Executar"
    id: "7889796f-033f-450d-97dd-6fee2a44f1b1"
  - name: "Aguardando instruções"
    id: "dd9d1b1b-f842-4777-984d-c05ec6b6d8a3"
  - name: "Concluido"
    id: "db544ddc-a07d-47a9-8737-40c6be25f7ec"

# Mapeamento de categorias para IDs (atualizado com dados do ClickUp)
category_mappings:
  "Agendamentos":
    id: "4b6cd768-fb58-48a5-a3d3-6993d2026764"
  "Compras":
    id: "11155a3f-5b4a-46f0-a447-4753bd9c3682"
  "Documentos":
    id: "60b9e5ad-7135-473c-97b2-c18d99b4a2b1"
  "Lazer":
    id: "d12372bc-b2c1-4b15-b444-7edc7e477362"
  "Logística":
    id: "e94fdbaa-7442-4579-8f98-3d345a5a862b"
  "Viagens":
    id: "632bf51e-dc85-44de-8dc7-7d5cd2cdcd5e"
  "Plano de Saúde":
    id: "c99d911f-595b-45c4-bb01-15d627d5a62f"
  "Agenda":
    id: "c2ebd410-5ec1-4eb4-b585-d6bb9a9b9ff3"
  "Financeiro":
    id: "6c7b5c2c-1d11-4198-8a54-6a748ef750a8"
  "Assuntos Pessoais":
    id: "72c6a009-bce5-41db-870f-c29d7094dbaf"
  "Atividades Corporativas":
    id: "5baa7715-1dfa-4a36-8452-78d60748e193"
  "Gestão de Funcionário":
    id: "b0118e0d-1ae9-4275-bda1-c7651eb8c7d0"

# Subcategorias por categoria (com IDs e estrelas)
subcategory_mappings:
  "Agendamentos":
    - name: "Consultas"
      id: "bff3cb1c-a75c-42e3-8249-18dbe32296f7"
      stars: 1
    - name: "Exames"
      id: "279d40c2-7856-4c74-9190-0b344172ce04"
      stars: 1
    - name: "Veterinário/Petshop (Consultas/Exames/Banhos/Tosas)"
      id: "dfa4f25f-e67c-42e7-a654-a29bba148635"
      stars: 1
    - name: "Vacinas"
      id: "9f6b7d48-e72f-41a5-9998-8fd67e7c0348"
      stars: 1
    - name: "Manicure"
      id: "edf4e00d-bc90-4731-9390-77ee25d8f212"
      stars: 1
    - name: "Cabeleleiro"
      id: "8eb7dd7c-a67d-4ff6-9ca7-1134687610b6"
      stars: 1
  "Compras":
    - name: "Shopper"
      id: "ae9c9144-0676-46ec-b9aa-dcae536d2d82"
      stars: 2
    - name: "Mercados"
      id: "6d77b238-5e18-45c8-bce1-502347793853"
      stars: 1
    - name: "Presentes"
      id: "ff7ebf1d-e28b-4759-9601-480b67815ca4"
      stars: 1
    - name: "Petshop"
      id: "b9fbb46e-95f2-4273-8c93-442dfaaff42f"
      stars: 1
    - name: "Papelaria"
      id: "101a73fe-9ae7-4e66-bddf-e736e6538d37"
      stars: 1
    - name: "Farmácia"
      id: "a8944553-7f2a-41d9-a2ca-dc2c4f734ac8"
      stars: 2
    - name: "Ingressos"
      id: "ac4019ae-ed29-4e10-b342-203029295d54"
      stars: 2
    - name: "Móveis e Eletros"
      id: "576fe8f0-8aab-4dca-b11b-94c9f7f7a67c"
      stars: 2
    - name: "Itens pessoais e da casa"
      id: "e161df73-4977-4642-a116-6b21802092a7"
      stars: 2
  "Documentos":
    - name: "CIN"
      id: "3be771dc-7efe-44de-bc66-8ab833537e75"
      stars: 1
    - name: "Certificado Digital"
      id: "1ad5c593-6b54-4673-83f7-a239d981fe72"
      stars: 2
    - name: "Documento de Vacinação (BR/Iternacional)"
      id: "12980d4b-c4bd-4ed7-b36d-060422d023da"
      stars: 1
    - name: "Seguros Carro/Casa/Viagem (anual)"
      id: "6745d1ec-2083-4883-bdb0-00fccd1015f0"
      stars: 2
    - name: "Assinatura Digital"
      id: "94d4ef32-e631-42ca-87e1-aafb5ddbdcf8"
      stars: 1
    - name: "Contratos/Procurações"
      id: "afc11da3-774f-4560-a92d-6d41c1b5eb60"
      stars: 1
    - name: "Cidadanias"
      id: "8fd5c543-fd90-4c07-be5e-a470f25c41a0"
      stars: 4
    - name: "Vistos e Vistos Eletrônicos"
      id: "b9a5bac8-e0ad-46f4-9309-9b2ee5acdcf4"
      stars: 2
    - name: "Passaporte"
      id: "04cd634f-28fa-41bb-9f66-dae43c3438ca"
      stars: 1
    - name: "CNH"
      id: "a39b0909-862b-4ead-a20a-26a1846a2ba1"
      stars: 1
    - name: "Averbações"
      id: "50447800-2557-4653-8874-79bc40473624"
      stars: 1
    - name: "Certidões"
      id: "3c90b607-8bab-40f6-b96d-75f2888ad9aa"
      stars: 1
  "Lazer":
    - name: "Reserva de restaurantes/bares"
      id: "99e3c2b5-e89f-4095-bcf5-7cdc27a36052"
      stars: 1
    - name: "Planejamento de festas"
      id: "75714f82-0366-429e-9131-4e91e925cf61"
      stars: 4
    - name: "Pesquisa de passeios/eventos (BR)"
      id: "2329a8b6-3d57-4136-b62a-4668cf88a7b6"
      stars: 3
    - name: "Fornecedores no exterior (passeios, fotógrafos)"
      id: "7ae92403-be05-4a57-890c-b2e6d5a8a3be"
      stars: 2
  "Logística":
    - name: "Corrida de motoboy"
      id: "bbb7859d-5f9a-46ac-a1dc-31a2f50c3bf8"
      stars: 1
    - name: "Motoboy + Correios e envios internacionais"
      id: "e536f830-09f9-4643-9c96-a368f7751621"
      stars: 1
    - name: "Lalamove"
      id: "0f5385b3-f4bf-4fda-8024-cb68bcfb8081"
      stars: 1
    - name: "Corridas com Taxistas"
      id: "88e88662-8417-4289-8984-26fd9eef47ef"
      stars: 1
    - name: "Transporte Urbano (Uber/99)"
      id: "1aea6ab4-24c4-405c-9165-8439fe648e51"
      stars: 1
  "Viagens":
    - name: "Passagens Aéreas"
      id: "790f6daf-a1f8-4dcb-a2fb-9b13a635af7b"
      stars: 2
    - name: "Hospedagens"
      id: "a7b1efc0-21fb-43be-a1ce-093469a605a0"
      stars: 2
    - name: "Compra de Assentos e Bagagens"
      id: "8e1e0e3f-c8d7-4d45-bee0-2fd7872fa1ce"
      stars: 1
    - name: "Passagens de Ônibus"
      id: "43196e32-64bf-4e18-931b-71d1f55bc1f2"
      stars: 1
    - name: "Passagens de Trem"
      id: "c16c703c-a0bb-4b16-8b41-a0648d41b267"
      stars: 2
    - name: "Checkins (Early/Late)"
      id: "d40e5677-26b9-4191-885a-f23e6c19e905"
      stars: 1
    - name: "Extravio de Bagagens"
      id: "812ae904-2273-4793-8228-eba85228b685"
      stars: 2
    - name: "Seguro Viagem (Temporário)"
      id: "775b4b9b-f9d4-4cec-bba9-df233acd1f96"
      stars: 1
    - name: "Transfer"
      id: "ba110e55-104c-45f7-9302-bd8e14113c37"
      stars: 2
    - name: "Programa de Milhagem"
      id: "23d3e4cd-7d6d-4c0e-be26-2a771e0e8734"
      stars: 1
    - name: "Gestão de Contas (CIAs Aereas)"
      id: "960167db-afb7-48dc-b8e8-12d8f695611a"
      stars: 1
    - name: "Aluguel de Carro/Ônibus e Vans"
      id: "78df793d-3a57-4f33-baa2-1ec35e93a39c"
      stars: 2
    - name: "Roteiro de Viagens"
      id: "b4b361fc-6d60-40b5-9c41-74f54d8d1ec7"
      stars: 3
  "Plano de Saúde":
    - name: "Reembolso Médico"
      id: "76b0f31e-f8a1-4fcb-baca-7fc14bde2b30"
      stars: 2
    - name: "Extrato para IR"
      id: "54373456-c0c6-4a7b-87fb-2332831e2d98"
      stars: 1
    - name: "Prévia de Reembolso"
      id: "8ae20f10-16ea-4294-8e3b-cb83c64f7cdb"
      stars: 1
    - name: "Contestações"
      id: "af6f081a-49a9-414b-82c4-ddee43fbfb2e"
      stars: 1
    - name: "Autorizações"
      id: "5c805f34-4479-4ec3-8822-5dffe5489124"
      stars: 1
    - name: "Contratações/Cancelamentos"
      id: "2fdb5cc9-18a7-451d-be47-c184e537855e"
      stars: 2
  "Agenda":
    - name: "Gestão de Agenda"
      id: "45f0fa60-db1c-4343-93b0-111f1db221e1"
      stars: 1
    - name: "Criação e envio de invites"
      id: "4a7728a4-1754-4325-9dc9-400a7209da9e"
      stars: 1
  "Financeiro":
    - name: "Emissão de NF"
      id: "530e1f11-b1a1-4505-bce5-76bc873dbdb4"
      stars: 1
    - name: "Rotina de Pagamentos"
      id: "1a84d897-b53c-4713-b526-60eb5c965aab"
      stars: 1
    - name: "Emissão de boletos"
      id: "b88bc587-6b13-47ec-a393-793ab335404e"
      stars: 1
    - name: "Conciliação Bancária"
      id: "f01ad326-41e7-4d1e-914e-9457eabf9e30"
      stars: 2
    - name: "Planilha de Gastos/Pagamentos"
      id: "af184e5d-bc21-4715-b792-1310e41cef12"
      stars: 4
    - name: "Encerramento e Abertura de CNPJ"
      id: "88eb8b12-d65b-464a-923a-7d656ea95a23"
      stars: 2
    - name: "Imposto de Renda"
      id: "db04f3c8-7d9c-4adb-8a19-c033c189a0f9"
      stars: 1
    - name: "Emissão de Guias de Imposto (DARF, DAS, DIRF, GPS)"
      id: "c2e61adb-92c8-4562-a9b2-8629e2f4a493"
      stars: 1
  "Assuntos Pessoais":
    - name: "Mudanças"
      id: "b77afa16-4a74-4a09-abe6-ccb7338d5b8d"
      stars: 3
    - name: "Troca de titularidade"
      id: "2b9ecf23-5873-4a26-8b4d-36f9f7498421"
      stars: 1
    - name: "Assuntos do Carro/Moto"
      id: "c29d6435-7ed8-4324-af46-ff45eab5fa97"
      stars: 1
    - name: "Internet e TV por Assinatura"
      id: "3613c025-d6bb-48a1-9cf4-e1b73f837d61"
      stars: 1
    - name: "Contas de Consumo"
      id: "dd76b9a0-18e6-41cc-ade3-23add30748a7"
      stars: 1
    - name: "Anúncio de Vendas Online (Itens, eletros. móveis)"
      id: "c09ff878-ff56-401a-b51a-7a06d4af2015"
      stars: 3
    - name: "Assuntos Escolares e Professores Particulares"
      id: "18d4ff39-f15b-493a-9082-057b0b33ba8d"
      stars: 1
    - name: "Academia e Cursos Livres"
      id: "62a15b40-5462-4886-8fa3-bc8ace5008bc"
      stars: 1
    - name: "Telefone"
      id: "bff82ef1-6193-4f13-a363-b6bcfa7694e2"
      stars: 1
    - name: "Assistência Técnica"
      id: "4ff47999-34af-4e6b-8c68-11974bc6c56d"
      stars: 1
    - name: "Consertos na Casa"
      id: "e1262c25-ace2-4c19-bff3-bc56662f98a6"
      stars: 1
  "Atividades Corporativas":
    - name: "Financeiro/Contábil"
      id: "9de0acb5-2451-4531-adb5-08e0e929996e"
      stars: 1
    - name: "Atendimento ao Cliente"
      id: "5f8c3193-31da-46fc-ba67-0b67bb87fea0"
      stars: 1
    - name: "Gestão de Planilhas e Emails"
      id: "744ec6fb-7d28-43a1-a02d-fca5148993e9"
      stars: 4
    - name: "Documentos/Contratos e Assinaturas"
      id: "43d79a01-7c60-4902-a308-6a708c8ff6b0"
      stars: 1
    - name: "Gestão de Agenda (Corporativa)"
      id: "f06a6de8-dd51-4df5-895c-d7b3495c1f5c"
      stars: 1
    - name: "Recursos Humanos"
      id: "e301567c-e1d4-4095-a709-835b26538e0f"
      stars: 1
    - name: "Gestão de Estoque"
      id: "82e3ba06-5125-4357-9b0e-3096a8ca6820"
      stars: 1
    - name: "Compras/vendas"
      id: "3c72d198-f18b-4747-8b39-302209e7b11d"
      stars: 1
    - name: "Fornecedores"
      id: "e42cab5b-6c54-4b70-8616-1ae96bbe0568"
      stars: 2
  "Gestão de Funcionário":
    - name: "eSocial"
      id: "26b11372-6bbc-4a36-aa5c-2b0cde733413"
      stars: 1
    - name: "Contratações e Desligamentos"
      id: "3f14982e-5047-48df-95f3-671fd55bd1da"
      stars: 1
    - name: "DIRF"
      id: "168420f6-f02e-4d80-af97-840411973461"
      stars: 1
    - name: "Férias"
      id: "3de88e9f-09f2-4a9e-84d9-eff5f987b344"
      stars: 1

# Template para categorias - será substituído com valores reais do ClickUp
categories_template: |
  CATEGORIAS DISPONÍVEIS NO CLICKUP:
  {{categories_list}}

# Template para tipos de atividade
activity_types_template: |
  TIPO DE ATIVIDADE:
  {{activity_types_list}}

# Template para status
status_template: |
  STATUS BACK OFFICE:
  {{status_list}}

# Template para subcategorias
subcategories_template: |
  SUBCATEGORIAS DISPONÍVEIS (relacionadas às categorias):
  {{subcategories_list}}
  
  IMPORTANTE: A subcategoria SEMPRE deve ser relacionada à categoria principal escolhida.

# Regras fixas que sempre se aplicam
rules:
  - "A subcategoria SEMPRE deve ser relacionada à categoria principal escolhida"
  - "Para agendamentos (consultas, exames, veterinário, etc): escolha a categoria Agendamentos"
  - "Para pedidos de compra (mercado, presentes, farmácia, etc): escolha a categoria Compras"
  - "Para documentos (passaporte, CNH, certidões, etc): escolha a categoria Documentos"
  - "Para lazer (restaurantes, festas, eventos): escolha a categoria Lazer"
  - "Para entregas/transporte (motoboy, uber, correios): escolha a categoria Logística"
  - "Para viagens (passagens, hospedagens, transfer): escolha a categoria Viagens"
  - "Para plano de saúde (reembolsos, autorizações): escolha a categoria Plano de Saúde"
  - "Para agenda (gestão de agenda, invites): escolha a categoria Agenda"
  - "Para financeiro (NF, pagamentos, IR): escolha a categoria Financeiro"
  - "Para assuntos pessoais (mudanças, carro, casa): escolha a categoria Assuntos Pessoais"
  - "Para atividades corporativas (RH, estoque, planilhas): escolha a categoria Atividades Corporativas"
  - "Para gestão de funcionários (eSocial, DIRF, férias): escolha a categoria Gestão de Funcionário"
  - "Se não houver certeza sobre a atividade, classifique como false"
  - "Sempre escolha valores EXATOS das listas fornecidas, não invente opções"
  - "Se uma subcategoria não se encaixar perfeitamente, deixe como null"

# Exemplos de mapeamento (para orientação)
mapping_examples:
  - categoria: "Agendamentos"
    exemplos_subcategorias:
      - "Consultas"
      - "Exames"
      - "Veterinário/Petshop (Consultas/Exames/Banhos/Tosas)"
      - "Vacinas"
  - categoria: "Compras"
    exemplos_subcategorias:
      - "Mercados"
      - "Presentes"
      - "Farmácia"
      - "Petshop"
  - categoria: "Documentos"
    exemplos_subcategorias:
      - "Passaporte"
      - "CNH"
      - "Certidões"
      - "Cidadanias"
  - categoria: "Lazer"
    exemplos_subcategorias:
      - "Reserva de restaurantes/bares"
      - "Planejamento de festas"
  - categoria: "Logística"
    exemplos_subcategorias:
      - "Corrida de motoboy"
      - "Motoboy + Correios e envios internacionais"
      - "Transporte Urbano (Uber/99)"
  - categoria: "Viagens"
    exemplos_subcategorias:
      - "Passagens Aéreas"
      - "Hospedagens"
      - "Transfer"
  - categoria: "Financeiro"
    exemplos_subcategorias:
      - "Emissão de NF"
      - "Rotina de Pagamentos"
      - "Imposto de Renda"

# Formato esperado da resposta
response_format: |
  Responda APENAS com JSON válido:
  {
    "is_activity": true/false,
    "reason": "título curto e profissional para a tarefa (máximo 5 palavras)",
    "tipo_atividade": "{{activity_types_exact}}",
    "category": "{{categories_exact}}",
    "sub_categoria": "{{subcategories_exact}} ou null se não aplicável",
    "subtasks": ["subtarefa 1", "subtarefa 2"] ou [],
    "status_back_office": "{{status_exact}}",
    "campanha": "título profissional da atividade",
    "description": "descrição detalhada da atividade",
    "info_1": "dados do webhook ChatGuru (campo personalizado ou payload)",
    "info_2": "dados do webhook ChatGuru (campo personalizado ou payload)"
  }
  
  IMPORTANTE:
  - Use APENAS valores exatos das listas fornecidas acima
  - tipo_atividade deve ser um dos valores da lista TIPO DE ATIVIDADE
  - category deve ser um dos valores da lista CATEGORIAS
  - sub_categoria deve ser um dos valores da lista SUBCATEGORIAS ou null
  - status_back_office deve ser um dos valores da lista STATUS BACK OFFICE

# Valores padrão caso a busca dinâmica falhe
fallback_values:
  categories:
    - "Agendamentos"
    - "Compras"
    - "Documentos"
    - "Lazer"
    - "Logística"
    - "Viagens"
    - "Plano de Saúde"
    - "Agenda"
    - "Financeiro"
    - "Assuntos Pessoais"
    - "Atividades Corporativas"
    - "Gestão de Funcionário"

  activity_types:
    - name: "Rotineira"
      description: "tarefas recorrentes e do dia a dia"
    - name: "Especifica"
      description: "tarefas pontuais com propósito específico"
    - name: "Dedicada"
      description: "tarefas que demandam dedicação especial"

  status_options:
    - "Executar"
    - "Aguardando instruções"
    - "Concluido"

# IDs dos campos customizados no ClickUp
field_ids:
  category_field_id: "eac5bbd3-4ff6-41ac-aa93-0a13a5a2c75a"
  subcategory_field_id: "5333c095-eb40-4a5a-b0c2-76bfba4b1094"
  activity_type_field_id: "f1259ffb-7be8-49ff-92f8-5ff9882888d0"
  status_field_id: "6abbfe79-f80b-4b55-9b4b-9bd7f65b6458"