last_updated: '2025-09-24T17:03:19.058Z'
clickup_list_id: '901300373349'
task_fields:
  Sub Categoria:
    id: 330d635b-b0be-4a4a-960c-3ff974d597c3
    type: drop_down
    name: Sub Categoria
  Status Back Office:
    id: 6abbfe79-f80b-4b55-9b4b-9bd7f65b6458
    type: drop_down
    name: Status Back Office
  Categoria:
    id: c19b4f95-1ff7-4966-b201-02905d33cec6
    type: drop_down
    name: Categoria
  Tipo de Atividade:
    id: f1259ffb-7be8-49ff-92f8-5ff9882888d0
    type: drop_down
    name: Tipo de Atividade
task_dropdown_options:
  Sub Categoria:
    - id: 49901a4b-2d46-429b-92a0-ee242982b030
      name: ADM
    - id: b01412cd-81c6-4495-9020-6f4258b23648
      name: Consultas/Exames/Vacinas/Manicure/Pet, etc
    - id: 0e2fa54b-048f-4d12-a0fe-2db16b030ed5
      name: Atividades Financeiras / Reembolso Corporativo
    - id: 4a106fb2-a2ee-4720-8715-9dd453bf2a44
      name: Atendimento ao Cliente
    - id: 43004146-90d4-451e-83ea-b60dd6d0a609
      name: Contratação de Fornecedores / Contratação de Funcionários
    - id: 54236c7a-6db4-4af2-bfde-0e8a6289e5bd
      name: Gestão e Planilhas e Emails
    - id: e4d81fdb-9a33-4f99-bd17-83cb7a74fe70
      name: Fup Documentos  / Assinatura Digital
    - id: 04b876ec-1ca4-4233-b839-e2264b7a95c5
      name: Gestão de Agenda / Gestão de Estoque
    - id: 6071b824-b481-4892-92ee-3d1f814649d3
      name: Social Media
    - id: 614d3333-aabb-4e30-8a86-589054f5ab24
      name: Planilhas/Organização Pessoal/Pet
    - id: 0c6e7635-5a8f-4f73-bfa3-34e26ff00290
      name: 'Carro - Assuntos em Geral '
    - id: f01b11d2-6432-46e7-bc1b-516588cdd853
      name: Encerramento Abertura  de CC / INSS / Empresa (CNPJ)
    - id: 05596bd0-9de2-4dec-9370-d8f5cdae27ca
      name: Internet/Telefone/Tv Assinatura /Gas/Luz/Assistencia Tecnica Casa / Consertos em Geral
    - id: 21974571-9c82-402a-99e7-bbcecf7c400e
      name: Vender/Comprar - Imóvel/ Móveis / Itens de Casa
    - id: e047dcd7-1ad6-47d7-8634-5d0bd6ed3262
      name: Presentes / Farmácia / Mercado / Marmitas / Fotos / Flores / Papelaria / Uniforme Escolar
    - id: 6db21c46-d85f-46b9-aae7-a474c6509b19
      name: 'Contratos / Procurações / Assinaturas '
    - id: 7a2c53d5-85de-42a3-a426-e2fffdeb17ee
      name: Passaporte/ RG / CNH / Imóvel / Seguros (Carro/Casa) / Traduções / Vistos (outros)
    - id: e7e75619-6665-48be-9235-ae08e58ffd84
      name: 'Visto Americano (Renovação) '
    - id: 3c190f43-db38-4a3a-8ec3-f091e7bb0144
      name: Visto Americano (1 visto)
    - id: 3129358e-7982-4ada-8ccf-7f26abb82a13
      name: Cidadania Europeia
    - id: afda5c39-56c0-491a-90c7-566914c56074
      name: Cartório - Reconhecimento de Firma / Apostilamentos
    - id: 72aa3197-f089-4231-914c-3f11e413ce6b
      name: 'Comprar / renovar Certificado Digital '
    - id: 8d727072-fb3b-4c2e-af0b-d8350c33b781
      name: Carteira de vacinação (BR/Internacional)
    - id: 1e74885f-70cd-4f12-9566-4e4027a753bc
      name: Escola / Faculdade / Academia (fazer matricula / checar grade / atividades extra curriculares)
    - id: bbb0a731-1b9e-4f1f-aa80-80de1d3cf808
      name: Evento Externo - Passagem / Hospedagem / Carro / Estrutura
    - id: f9d66477-6a02-448f-9573-7af7588bf489
      name: Offsites (Espaço de eventos)
    - id: d94bd26e-f58e-45c8-a8ec-8f1a4d4bdaca
      name: Offsites - contratar transfer (Van)
    - id: 38e4b91f-36f6-49cf-8a21-d0a32848f623
      name: Organizar Coffee Breaks / Catering
    - id: dcd2a33b-86b4-4d83-91c3-ef3f9de253ea
      name: 'ESocial (mensal / férias / 13 salario) / VT '
    - id: 8fa58985-e4a8-443a-b12d-bbbd429a684f
      name: 'Reserva de Restaurantes / Bar '
    - id: bf2f1612-8e98-47fb-869a-ca143057b891
      name: Organização de Festa Adulto
    - id: 1c6fe740-f11a-458c-9734-063a39d7ccf0
      name: Organização de Festa Infantil
    - id: 5a4393b9-da8d-4c99-a49f-70413f124d8b
      name: ' Ingressos de Shows, Exposições, Eventos, Festas e Passeios'
    - id: dfc2ce4f-568a-4397-874f-62c0bdc1e81a
      name: Motoboy / Uber / Loggi / Correios
    - id: 7f4fca82-98d9-4c12-8bd8-0f345eb38375
      name: 'Mudança '
    - id: 02c0dcac-6dc9-483b-913b-2db13825ee09
      name: Controle de Gastos Mensais (Planilhas)
    - id: 1e9fd3b8-1bb8-4099-8861-99b49c3d1636
      name: 'Debito Automatico / Pagamentos Pendentes / 2 Via '
    - id: dba6761c-83a7-4cd7-bfba-f550d03e2f06
      name: Pagamentos via Friday / envio de codigo de barras
    - id: 3646d3bb-83ae-41c2-8f73-941050b702e8
      name: Guias DARF (INSS) / MEI para pagamento
    - id: ea8b81c8-b16e-49e5-a83d-14048b055466
      name: 'Envio de NF para reembolso '
    - id: 9566759c-0586-434a-9ad0-75633845c60d
      name: Solicitar Autorização / Contestação / Extrato para IR / Previa de Reembolso / Reclamação
    - id: 59b2dad2-ec38-4a09-8810-005363808045
      name: Contratação / Cancelamento
    - id: 4209e07f-f1d9-4f1c-96ac-f8652af7b47e
      name: 'Documentação (Regras Sanitárias / vistos / vacinas) '
    - id: 99edd737-20d9-4daa-8a80-40e52ad3c269
      name: 'Extravio de Malas e Bagagens '
    - id: e75df77b-7837-4917-b328-cfb5235deb77
      name: 'Fazer Check in Voos '
    - id: 9d9e22c3-9372-42db-81b2-c3112421a567
      name: Hospedagem - Pesquisar / Cotar / Comprar / Cancelar
    - id: 3ddb02a9-8013-4d4e-b1c3-1e54a76a06eb
      name: 'Passagem de ônibus - Pesquisar / Cotar / Comprar '
    - id: 9ff811a8-b543-489d-a90f-03220dbaccad
      name: Passagem Aérea - Pesquisar / Cotar / Comprar / Cancelar
    - id: 99be807b-6188-4dc9-9bf8-aae51b06631b
      name: Programa de Milhagem / Cadastros e Alteração de Cadastros CIAS
    - id: 563deaa4-e717-4da4-a0b1-7066a40b9986
      name: 'Seguro Viagem - Pesquisar / Cotar / Comprar '
    - id: f63a9631-d786-4564-88af-05f03b3ff54d
      name: Transfer / Aluguel / Reserva de Carro / Cancelar
    - id: 6ff3b9ab-c3ae-493b-94eb-b69797b7b29a
      name: Pesquisas / Orçamento
    - id: 9cf26e9e-b3c4-4b09-9dc7-f00699db84ad
      name: Emissão de NF
    - id: 829e9da1-e7f1-465c-988d-856ddecf3aa1
      name: Controle Interno
    - id: cfcc3734-81f6-4d16-92db-6b51ee95986c
      name: IR/IR MEI
  Status Back Office:
    - id: db544ddc-a07d-47a9-8737-40c6be25f7ec
      name: Concluido
    - id: dd9d1b1b-f842-4777-984d-c05ec6b6d8a3
      name: Aguardando instruções
    - id: 7889796f-033f-450d-97dd-6fee2a44f1b1
      name: Executar
  Categoria:
    - id: a4a4e85c-4eb5-44f9-9175-f98594da5c70
      name: ADM
    - id: 25102629-2b4f-4863-847c-51468e484362
      name: Agendamento
    - id: e0b80ba4-3b2e-47bc-9a4f-d322045d6480
      name: Atividades Corporativas
    - id: 1b61be8c-6eaa-4cd4-959d-c48f8b78ca3e
      name: Atividades Pessoais / Domésticas
    - id: 4799d43c-c1be-478e-ad58-57fdfa95b292
      name: Compras
    - id: e57a5888-49cc-4c3a-bb4a-e235c8c58e77
      name: Documentos
    - id: 4232858d-8052-4fdc-9ce9-628f34d2edac
      name: Educação / Academia
    - id: 07c402c5-1f0b-4ae0-b38e-349553fd7a81
      name: Eventos Corporativos
    - id: 2330057a-4637-4ab6-94af-905904fdb4c3
      name: Gestão de Funcionário Doméstico
    - id: 68539506-88b8-44a5-bac8-0496b2b2f148
      name: Lazer
    - id: a1bc0a49-2a9d-41bd-a91a-a6b4af7677b4
      name: Logistica
    - id: 18c2c60c-cfd0-4ef8-af94-7542bd9b30c7
      name: Festas / Reuniões / Recepção
    - id: b64b9e80-fdc4-4521-8975-45e335109b49
      name: Pagamentos
    - id: 80ad2f74-7074-4eec-a4fd-8fc92d0fe0dd
      name: Pesquisas / Orçamentos
    - id: 3496ba6c-9d7f-495f-951e-6017dfdbd55b
      name: Plano de Saúde
    - id: 2aebf637-6534-487c-bd35-d28334c8d685
      name: Viagens
    - id: 16c6bd8a-05d3-4bd7-8fd9-906ef3e8b2d2
      name: Controle Interno
    - id: 8fb02d9e-febb-4b94-9e9e-cdf8ff5a28fb
      name: Compra/Venda/Aluguel
    - id: 14f5e8ff-df26-4446-8766-053e47c001c7
      name: Atividade Baixada/Duplicada
  Tipo de Atividade:
    - id: 64f034f3-c5db-46e5-80e5-f515f11e2131
      name: Rotineira
    - id: e85a4dc7-82d8-4f63-89ee-462232f50f31
      name: Especifica
    - id: 6c810e95-f5e8-4e8f-ba23-808cf555046f
      name: Dedicada
categories:
  - ADM
  - Agendamento
  - Atividades Corporativas
  - Atividades Pessoais / Domésticas
  - Compras
  - Documentos
  - Educação / Academia
  - Eventos Corporativos
  - Gestão de Funcionário Doméstico
  - Lazer
  - Logistica
  - Festas / Reuniões / Recepção
  - Pagamentos
  - Pesquisas / Orçamentos
  - Plano de Saúde
  - Viagens
  - Controle Interno
  - Compra/Venda/Aluguel
  - Atividade Baixada/Duplicada
activity_types:
  - name: Rotineira
    description: tarefas recorrentes e do dia a dia
  - name: Especifica
    description: tarefas pontuais com propósito específico
  - name: Dedicada
    description: tarefas que demandam dedicação especial
status_options:
  - Concluido
  - Aguardando instruções
  - Executar
subcategories:
  - ADM
  - Consultas/Exames/Vacinas/Manicure/Pet, etc
  - Atividades Financeiras / Reembolso Corporativo
  - Atendimento ao Cliente
  - Contratação de Fornecedores / Contratação de Funcionários
  - Gestão e Planilhas e Emails
  - Fup Documentos  / Assinatura Digital
  - Gestão de Agenda / Gestão de Estoque
  - Social Media
  - Planilhas/Organização Pessoal/Pet
  - 'Carro - Assuntos em Geral '
  - Encerramento Abertura  de CC / INSS / Empresa (CNPJ)
  - Internet/Telefone/Tv Assinatura /Gas/Luz/Assistencia Tecnica Casa / Consertos em Geral
  - Vender/Comprar - Imóvel/ Móveis / Itens de Casa
  - Presentes / Farmácia / Mercado / Marmitas / Fotos / Flores / Papelaria / Uniforme Escolar
  - 'Contratos / Procurações / Assinaturas '
  - Passaporte/ RG / CNH / Imóvel / Seguros (Carro/Casa) / Traduções / Vistos (outros)
  - 'Visto Americano (Renovação) '
  - Visto Americano (1 visto)
  - Cidadania Europeia
  - Cartório - Reconhecimento de Firma / Apostilamentos
  - 'Comprar / renovar Certificado Digital '
  - Carteira de vacinação (BR/Internacional)
  - Escola / Faculdade / Academia (fazer matricula / checar grade / atividades extra curriculares)
  - Evento Externo - Passagem / Hospedagem / Carro / Estrutura
  - Offsites (Espaço de eventos)
  - Offsites - contratar transfer (Van)
  - Organizar Coffee Breaks / Catering
  - 'ESocial (mensal / férias / 13 salario) / VT '
  - 'Reserva de Restaurantes / Bar '
  - Organização de Festa Adulto
  - Organização de Festa Infantil
  - ' Ingressos de Shows, Exposições, Eventos, Festas e Passeios'
  - Motoboy / Uber / Loggi / Correios
  - 'Mudança '
  - Controle de Gastos Mensais (Planilhas)
  - 'Debito Automatico / Pagamentos Pendentes / 2 Via '
  - Pagamentos via Friday / envio de codigo de barras
  - Guias DARF (INSS) / MEI para pagamento
  - 'Envio de NF para reembolso '
  - Solicitar Autorização / Contestação / Extrato para IR / Previa de Reembolso / Reclamação
  - Contratação / Cancelamento
  - 'Documentação (Regras Sanitárias / vistos / vacinas) '
  - 'Extravio de Malas e Bagagens '
  - 'Fazer Check in Voos '
  - Hospedagem - Pesquisar / Cotar / Comprar / Cancelar
  - 'Passagem de ônibus - Pesquisar / Cotar / Comprar '
  - Passagem Aérea - Pesquisar / Cotar / Comprar / Cancelar
  - Programa de Milhagem / Cadastros e Alteração de Cadastros CIAS
  - 'Seguro Viagem - Pesquisar / Cotar / Comprar '
  - Transfer / Aluguel / Reserva de Carro / Cancelar
  - Pesquisas / Orçamento
  - Emissão de NF
  - Controle Interno
  - IR/IR MEI
field_ids:
  category_field_id: c19b4f95-1ff7-4966-b201-02905d33cec6
  subcategory_field_id: 330d635b-b0be-4a4a-960c-3ff974d597c3
  activity_type_field_id: f1259ffb-7be8-49ff-92f8-5ff9882888d0
  status_field_id: 6abbfe79-f80b-4b55-9b4b-9bd7f65b6458
